SELECT fp.CATEGORY, fp.PRICE AS MAX_PRICE, fp.PRODUCT_NAME
FROM FOOD_PRODUCT fp
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) TEMP
ON fp.CATEGORY = TEMP.CATEGORY
AND fp.PRICE = TEMP.MAX_PRICE
ORDER BY fp.PRICE DESC;